In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../course_data/DATA/Advertising.csv')
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [3]:
X = df.drop('sales', axis=1)

In [4]:
y = df['sales']

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
scaler = StandardScaler()

In [9]:
scaler.fit(X_train)

StandardScaler()

In [10]:
X_train = scaler.transform(X_train)

In [11]:
X_test = scaler.transform(X_test)

In [12]:
from sklearn.linear_model import Ridge

In [13]:
model = Ridge(alpha=100)

In [14]:
from sklearn.model_selection import cross_val_score

In [15]:
scores = cross_val_score(model, X_train, y_train, scoring='neg_mean_squared_error', cv=5)

In [16]:
scores

array([ -9.32552967,  -4.9449624 , -11.39665242,  -7.0242106 ,
        -8.38562723])

In [17]:
abs(scores.mean())

np.float64(8.215396464543607)

In [18]:
model = Ridge(alpha=1)

In [19]:
scores = cross_val_score(model, X_train, y_train, scoring='neg_mean_squared_error', cv=5)

In [20]:
abs(scores.mean())

np.float64(3.344839296530695)

In [21]:
model.fit(X_train, y_train)

Ridge(alpha=1)

In [22]:
y_final_test_pred = model.predict(X_test)

In [23]:
from sklearn.metrics import mean_squared_error

In [24]:
mean_squared_error(y_test, y_final_test_pred)

2.319021579428752

### Кросс-валидация с помощью cross_validate

In [30]:
# Создаем Х и y
X = df.drop('sales', axis=1)
y = df['sales']

# Делаем разбиение на TRAIN и TEST
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

# 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [36]:
from sklearn.model_selection import cross_validate

In [37]:
model = Ridge(alpha=100)

In [41]:
sdf

In [42]:
scores

{'fit_time': array([0.00554776, 0.00205016, 0.00222564, 0.00194025, 0.00148511,
        0.00149703, 0.00165772, 0.0019598 , 0.00245023, 0.00191736]),
 'score_time': array([0.00270438, 0.00192356, 0.00173068, 0.00194788, 0.00154448,
        0.00160003, 0.00141549, 0.00160074, 0.00240159, 0.00184107]),
 'test_neg_mean_squared_error': array([ -6.06067062, -10.62703078,  -3.99342608,  -5.00949402,
         -9.14179955, -13.08625636,  -3.83940454,  -9.05878567,
         -9.05545685,  -5.77888211]),
 'test_neg_mean_absolute_error': array([-1.8102116 , -2.54195751, -1.46959386, -1.86276886, -2.52069737,
        -2.45999491, -1.45197069, -2.37739501, -2.44334397, -1.89979708])}

In [44]:
scores = pd.DataFrame(scores)
scores

,fit_time,score_time,test_neg_mean_squared_error,test_neg_mean_absolute_error
0,0.005548,0.002704,-6.060671,-1.810212
1,0.002050,0.001924,-10.627031,-2.541958
2,0.002226,0.001731,-3.993426,-1.469594
3,0.001940,0.001948,-5.009494,-1.862769
4,0.001485,0.001544,-9.141800,-2.520697
5,0.001497,0.001600,-13.086256,-2.459995
6,0.001658,0.001415,-3.839405,-1.451971
7,0.001960,0.001601,-9.058786,-2.377395
8,0.002450,0.002402,-9.055457,-2.443344
9,0.001917,0.001841,-5.778882,-1.899797

In [45]:
scores.mean()

fit_time                        0.002273
score_time                      0.001871
test_neg_mean_squared_error    -7.565121
test_neg_mean_absolute_error   -2.083773
dtype: float64

In [48]:
model = Ridge(alpha=1)

In [49]:
scores = cross_validate(model, X_train, y_train, scoring=['neg_mean_squared_error', 'neg_mean_absolute_error'], cv=10)

In [50]:
scores = pd.DataFrame(scores)
scores

,fit_time,score_time,test_neg_mean_squared_error,test_neg_mean_absolute_error
0,0.004009,0.003944,-2.962508,-1.457174
1,0.003907,0.003686,-3.057378,-1.555308
2,0.002800,0.002437,-2.173740,-1.238770
3,0.002246,0.001913,-0.833034,-0.768938
4,0.001706,0.001682,-3.464018,-1.434489
5,0.001504,0.001441,-8.232647,-1.494316
6,0.001411,0.001392,-1.905864,-1.081362
7,0.003286,0.002388,-2.765048,-1.250011
8,0.001969,0.001617,-4.989505,-1.580971
9,0.001532,0.001517,-2.846438,-1.223326

In [51]:
scores.mean()

fit_time                        0.002437
score_time                      0.002202
test_neg_mean_squared_error    -3.323018
test_neg_mean_absolute_error   -1.308467
dtype: float64

In [52]:
model.fit(X_train, y_train)

Ridge(alpha=1)

In [53]:
y_final_pred = model.predict(X_test)

In [54]:
y_final_pred = model.predict(X_test)

In [ ]:
mean_squared_error()