### Данные
Однажды был проведен эксперимент - на 5000 участниках проверяли, как возраст и физическое здоровье влияют на потерю слуха, особенно на способность слышать высокие тона. 
 - Признаки
   - age - возраст участников в годах
   - physical_score - оценка физическаого здоровья, полученная в результате физических тестов
 - Целевая переменная (Label/Target)
   - test_results - 0 если аудио-тест не пройден и 1 - если аудио-тест пройден

In [8]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv('../course_data/DATA/hearing_test.csv')

In [13]:
df.head()

    age  physical_score  test_result
0  33.0            40.7            1
1  50.0            37.2            1
2  52.0            24.7            0
3  56.0            31.0            0
4  35.0            42.9            1

In [14]:
df.describe()

               age  physical_score  test_result
count  5000.000000     5000.000000  5000.000000
mean     51.609000       32.760260     0.600000
std      11.287001        8.169802     0.489947
min      18.000000       -0.000000     0.000000
25%      43.000000       26.700000     0.000000
50%      51.000000       35.300000     1.000000
75%      60.000000       38.900000     1.000000
max      90.000000       50.000000     1.000000